# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 wahke <info@wahke.lu> (https://wahke.lu)
# SPDX-FileCopyrightText: 2026 VanguardMod Project Contributors
"""Unit tests for the CLI dispatcher.

Tests call ``cli.main([...])`` directly with explicit argv, so they
don't shell out and don't pay the GUI import cost. The no-subcommand
GUI default path is intentionally not unit-tested — it's tkinter
mainloop, exercised manually and on CI via the smoke import.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from vanguard_config_builder import cli


# ---------------------------------------------------------------------------
# generate
# ---------------------------------------------------------------------------
class TestGenerate:
    def test_writes_a_cfg_file(self, tmp_path: Path) -> None:
        out = tmp_path / "server.cfg"
        rc = cli.main(["generate", "--profile", "cup", "-o", str(out)])
        assert rc == cli.EXIT_SUCCESS
        text = out.read_text(encoding="utf-8")
        assert "Generated by Config Builder" in text
        assert "Cup / Tournament" in text  # profile_name in header
        assert "seta sv_fps" in text       # archived cvar

    def test_no_header_skips_metadata_block(self, tmp_path: Path) -> None:
        out = tmp_path / "server.cfg"
        rc = cli.main([
            "generate", "--profile", "public",
            "-o", str(out), "--no-header",
        ])
        assert rc == cli.EXIT_SUCCESS
        assert "Generated by Config Builder" not in out.read_text()

    def test_strict_default_on(self, tmp_path: Path) -> None:
        # The bundled profiles all validate clean, so --strict default-on
        # must not block the write. This is the contract that the
        # default profiles ship in a state CI can use.
        out = tmp_path / "server.cfg"
        rc = cli.main(["generate", "--profile", "scrim", "-o", str(out)])
        assert rc == cli.EXIT_SUCCESS
        assert out.is_file()

    def test_unknown_profile_returns_io_error(self, tmp_path: Path) -> None:
        out = tmp_path / "server.cfg"
        rc = cli.main([
            "generate", "--profile", "totally_made_up", "-o", str(out),
        ])
        assert rc == cli.EXIT_IO
        assert not out.exists()

    def test_unwritable_path_returns_io_error(self, tmp_path: Path) -> None:
        out = tmp_path / "no_such_dir" / "server.cfg"  # parent dir absent
        rc = cli.main(["generate", "--profile", "cup", "-o", str(out)])
        assert rc == cli.EXIT_IO


# ---------------------------------------------------------------------------
# validate
# ---------------------------------------------------------------------------
class TestValidate:
    def test_clean_cfg_returns_success(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str],
    ) -> None:
        # Generate a clean cfg first, then validate it.
        cfg = tmp_path / "server.cfg"
        cli.main(["generate", "--profile", "cup", "-o", str(cfg)])
        capsys.readouterr()                       # discard generate output

        rc = cli.main(["validate", str(cfg)])
        captured = capsys.readouterr()
        assert rc == cli.EXIT_SUCCESS
        assert "OK" in captured.out

    def test_dirty_cfg_returns_validation_exit(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str],
    ) -> None:
        cfg = tmp_path / "broken.cfg"
        cfg.write_text('seta sv_fps "9999"\n', encoding="utf-8")

        rc = cli.main(["validate", str(cfg)])
        captured = capsys.readouterr()
        assert rc == cli.EXIT_VALIDATION
        assert "out of range" in captured.out

    def test_json_format_is_parseable(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str],
    ) -> None:
        cfg = tmp_path / "broken.cfg"
        cfg.write_text('seta sv_fps "9999"\n', encoding="utf-8")

        rc = cli.main(["validate", str(cfg), "--format", "json"])
        assert rc == cli.EXIT_VALIDATION
        captured = capsys.readouterr()
        report = json.loads(captured.out)
        assert report["valid"] is False
        assert isinstance(report["issues"], list)
        assert any("out of range" in i for i in report["issues"])

    def test_missing_file_returns_io_error(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str],
    ) -> None:
        rc = cli.main(["validate", str(tmp_path / "nope.cfg")])
        assert rc == cli.EXIT_IO


# ---------------------------------------------------------------------------
# list-profiles
# ---------------------------------------------------------------------------
class TestListProfiles:
    def test_lists_three_user_visible(
        self, capsys: pytest.CaptureFixture[str],
    ) -> None:
        rc = cli.main(["list-profiles"])
        assert rc == cli.EXIT_SUCCESS
        out = capsys.readouterr().out
        # User-visible names appear in the leading stem column...
        stem_lines = [
            ln for ln in out.splitlines()
            if ln and not ln.startswith(" ")
        ]
        stems = {ln.split()[0] for ln in stem_lines}
        assert stems == {"cup", "public", "scrim"}
        # ..._base may still appear inside the chain caption (it's the
        # parent of every profile), but never as a top-level stem.
        assert "_base" not in stems


# ---------------------------------------------------------------------------
# list-cvars
# ---------------------------------------------------------------------------
class TestListCvars:
    def test_lists_all_24_in_text_mode(
        self, capsys: pytest.CaptureFixture[str],
    ) -> None:
        rc = cli.main(["list-cvars"])
        assert rc == cli.EXIT_SUCCESS
        out = capsys.readouterr().out
        # 24 cvar rows; each non-empty line starts with the cvar name.
        cvar_lines = [ln for ln in out.splitlines() if ln and not ln.startswith(" ")]
        assert len(cvar_lines) == 24

    def test_category_filter(
        self, capsys: pytest.CaptureFixture[str],
    ) -> None:
        rc = cli.main(["list-cvars", "--category", "network"])
        assert rc == cli.EXIT_SUCCESS
        out = capsys.readouterr().out
        # Network cvars should be present, identity ones absent.
        assert "sv_fps" in out
        assert "sv_hostname" not in out

    def test_unknown_category_returns_success_with_message(
        self, capsys: pytest.CaptureFixture[str],
    ) -> None:
        rc = cli.main(["list-cvars", "--category", "no_such_category"])
        assert rc == cli.EXIT_SUCCESS
        # No matches → message goes to stderr, exit is still 0.
        err = capsys.readouterr().err
        assert "no_such_category" in err

    def test_json_format_is_parseable(
        self, capsys: pytest.CaptureFixture[str],
    ) -> None:
        rc = cli.main(["list-cvars", "--format", "json"])
        assert rc == cli.EXIT_SUCCESS
        data = json.loads(capsys.readouterr().out)
        assert isinstance(data, list)
        assert len(data) == 24
        names = {entry["name"] for entry in data}
        assert "sv_fps" in names

    def test_secret_marker_in_text_output(
        self, capsys: pytest.CaptureFixture[str],
    ) -> None:
        rc = cli.main(["list-cvars", "--category", "identity"])
        assert rc == cli.EXIT_SUCCESS
        out = capsys.readouterr().out
        # rconpassword and g_password are secret in v0.1.0.
        rcon_line = next(ln for ln in out.splitlines() if "rconpassword" in ln)
        assert "[SECRET]" in rcon_line


# ---------------------------------------------------------------------------
# diff
# ---------------------------------------------------------------------------
class TestDiff:
    def test_identical_files_emit_no_differences(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str],
    ) -> None:
        cfg = tmp_path / "a.cfg"
        cli.main(["generate", "--profile", "cup", "-o", str(cfg)])
        capsys.readouterr()

        rc = cli.main(["diff", str(cfg), str(cfg)])
        captured = capsys.readouterr()
        assert rc == cli.EXIT_SUCCESS
        assert "no differences" in captured.out

    def test_changed_value_shows_arrow(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str],
    ) -> None:
        a = tmp_path / "a.cfg"
        b = tmp_path / "b.cfg"
        a.write_text('seta sv_fps "20"\n', encoding="utf-8")
        b.write_text('seta sv_fps "40"\n', encoding="utf-8")

        rc = cli.main(["diff", str(a), str(b)])
        out = capsys.readouterr().out
        assert rc == cli.EXIT_SUCCESS
        assert "~ sv_fps" in out
        assert "20" in out
        assert "40" in out

    def test_added_and_removed_lines(
        self, tmp_path: Path, capsys: pytest.CaptureFixture[str],
    ) -> None:
        a = tmp_path / "a.cfg"
        b = tmp_path / "b.cfg"
        a.write_text('seta sv_fps "20"\n', encoding="utf-8")
        b.write_text('seta sv_fps "20"\nseta g_antilag "1"\n',
                     encoding="utf-8")

        rc = cli.main(["diff", str(a), str(b)])
        out = capsys.readouterr().out
        assert rc == cli.EXIT_SUCCESS
        assert "+ g_antilag" in out

    def test_missing_file_returns_io_error(
        self, tmp_path: Path,
    ) -> None:
        rc = cli.main(["diff", str(tmp_path / "nope.cfg"),
                       str(tmp_path / "also_nope.cfg")])
        assert rc == cli.EXIT_IO


# ---------------------------------------------------------------------------
# Top-level
# ---------------------------------------------------------------------------
class TestParser:
    def test_version_flag_exits_zero(
        self, capsys: pytest.CaptureFixture[str],
    ) -> None:
        with pytest.raises(SystemExit) as exc:
            cli.main(["--version"])
        assert exc.value.code == 0
        out = capsys.readouterr().out
        assert "vanguard-config-builder" in out

    def test_help_lists_every_subcommand(
        self, capsys: pytest.CaptureFixture[str],
    ) -> None:
        with pytest.raises(SystemExit):
            cli.main(["--help"])
        out = capsys.readouterr().out
        for sub in ("generate", "validate", "list-profiles",
                    "list-cvars", "diff"):
            assert sub in out
