# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 wahke <info@wahke.lu> (https://wahke.lu)
# SPDX-FileCopyrightText: 2026 VanguardMod Project Contributors
"""Unit tests for ``core.cfg_generator``.

Tests in this module exercise the extracted core function directly with
small fixture data — no GUI import, no tkinter stub needed. The smoke
test suite still exercises the same behavior end-to-end via
``main.generate_cfg`` (the thin wrapper that injects the live CVARS
table); these tests pin down the contract of the core function in
isolation.

Once the project is repackaged as ``vanguard_config_builder`` (M9) the
import path will change to ``vanguard_config_builder.core.cfg_generator``
and a shared ``conftest.py`` will replace the per-file sys.path tweak.
"""
from __future__ import annotations

import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Make `core/` importable without installing the package. Mirrors the
# pattern in test_smoke.py so this file can run standalone via
# `python -m pytest tests/test_cfg_generator.py`.
# ---------------------------------------------------------------------------
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.cfg_generator import generate_cfg  # noqa: E402

# Minimal cvar table — enough to drive every code path without pulling in
# main.CVARS (which would require the tkinter stub). Mirrors the shape of
# the real CVARS dict.
_CVARS: dict[str, dict[str, object]] = {
    "sv_fps": {
        "type": "int",
        "default": 20,
        "range": (20, 125),
        "category": "network",
        "description": "tick rate",
        "archive": True,
        "secret": False,
    },
    "rconpassword": {
        "type": "string",
        "default": "",
        "range": None,
        "category": "identity",
        "description": "rcon",
        "archive": False,
        "secret": True,
    },
}

_VERSION = "0.1.0"


class TestGenerator:
    def test_produces_nonempty_output(self) -> None:
        values = {"sv_fps": 40, "rconpassword": "secret"}
        # pad the dict so we exceed 10 lines deterministically
        values.update({f"sv_fps_dup_{i}": i for i in range(20)})
        text = generate_cfg(values, _CVARS, _VERSION, profile_name="cup")
        assert text
        assert len(text.splitlines()) > 10

    def test_header_includes_metadata(self) -> None:
        text = generate_cfg({"sv_fps": 40}, _CVARS, _VERSION, profile_name="cup")
        assert "Generated by" in text
        assert "cup" in text

    def test_header_can_be_disabled(self) -> None:
        text = generate_cfg({"sv_fps": 40}, _CVARS, _VERSION, with_header=False)
        assert "Generated by" not in text

    def test_archive_cvars_use_seta(self) -> None:
        text = generate_cfg({"sv_fps": 40}, _CVARS, _VERSION, with_header=False)
        assert "seta sv_fps" in text

    def test_session_cvars_use_set(self) -> None:
        text = generate_cfg(
            {"rconpassword": "secret"}, _CVARS, _VERSION, with_header=False,
        )
        assert "set rconpassword" in text
        assert "seta rconpassword" not in text

    def test_unknown_cvar_warned_but_preserved(self) -> None:
        text = generate_cfg(
            {"some_future_cvar": "foo"}, _CVARS, _VERSION, with_header=False,
        )
        assert "WARNING: unknown cvar" in text
        assert "some_future_cvar" in text

    def test_version_lands_in_header(self) -> None:
        text = generate_cfg({"sv_fps": 40}, _CVARS, "9.9.9", profile_name="cup")
        assert "v9.9.9" in text
