"""Smoke tests for config-builder.

These tests stub out tkinter so they run in headless CI environments.
They cover the pure-Python parts: generator, parser, validator, and
profile dictionaries.

TODO Phase 2: Add proper unit tests once parser/generator/validator
              are split into their own modules.
TODO Phase 3: Add GUI tests via pytest-tk or similar.
"""
from __future__ import annotations

import sys
import types

import pytest


# ---------------------------------------------------------------------------
# tkinter stub — must be installed BEFORE importing main.py
# ---------------------------------------------------------------------------
def _install_tkinter_stub() -> None:
    for name in (
        "tkinter",
        "tkinter.ttk",
        "tkinter.filedialog",
        "tkinter.messagebox",
    ):
        if name not in sys.modules:
            sys.modules[name] = types.ModuleType(name)

    tk = sys.modules["tkinter"]
    # Just enough surface for the import to succeed.
    tk.IntVar = lambda value=0: types.SimpleNamespace(
        get=lambda: value, set=lambda v: None, trace_add=lambda *a, **kw: None
    )
    tk.StringVar = lambda value="": types.SimpleNamespace(
        get=lambda: value, set=lambda v: None, trace_add=lambda *a, **kw: None
    )
    for attr in ("Tk", "Text", "Canvas", "Menu", "Variable"):
        setattr(tk, attr, object)
    for attr in ("NW", "W", "LEFT", "RIGHT", "BOTH", "X", "Y", "END",
                 "HORIZONTAL", "VERTICAL", "NONE"):
        setattr(tk, attr, attr.lower())
    tk.TclError = Exception


_install_tkinter_stub()

# Now safe to import the module under test
sys.path.insert(0, str(__import__("pathlib").Path(__file__).parent.parent))
import main as m  # noqa: E402


# ---------------------------------------------------------------------------
# Generator tests
# ---------------------------------------------------------------------------
class TestGenerator:
    def test_produces_nonempty_output(self) -> None:
        text = m.generate_cfg(m.PROFILES["Cup / Tournament"], profile_name="cup")
        assert text
        assert len(text.splitlines()) > 10

    def test_header_includes_metadata(self) -> None:
        text = m.generate_cfg({"sv_fps": 40}, profile_name="cup")
        assert "Generated by" in text
        assert "cup" in text

    def test_header_can_be_disabled(self) -> None:
        text = m.generate_cfg({"sv_fps": 40}, with_header=False)
        assert "Generated by" not in text

    def test_archive_cvars_use_seta(self) -> None:
        text = m.generate_cfg({"sv_fps": 40}, with_header=False)
        # sv_fps is archive=True in the database
        assert "seta sv_fps" in text

    def test_session_cvars_use_set(self) -> None:
        text = m.generate_cfg({"rconpassword": "secret"}, with_header=False)
        # rconpassword is archive=False
        assert "set rconpassword" in text
        assert "seta rconpassword" not in text

    def test_unknown_cvar_warned_but_preserved(self) -> None:
        text = m.generate_cfg({"some_future_cvar": "foo"}, with_header=False)
        assert "WARNING: unknown cvar" in text
        assert "some_future_cvar" in text


# ---------------------------------------------------------------------------
# Parser tests
# ---------------------------------------------------------------------------
class TestParser:
    def test_parses_basic_seta(self) -> None:
        result = m.parse_cfg('seta sv_fps "40"')
        assert result == {"sv_fps": 40}

    def test_parses_basic_set(self) -> None:
        result = m.parse_cfg('set g_password "secret"')
        assert result == {"g_password": "secret"}

    def test_skips_comments(self) -> None:
        text = "// this is a comment\nseta sv_fps \"40\"\n// another"
        assert m.parse_cfg(text) == {"sv_fps": 40}

    def test_strips_inline_comments(self) -> None:
        result = m.parse_cfg('seta sv_fps "40" // tickrate')
        assert result == {"sv_fps": 40}

    def test_skips_blank_lines(self) -> None:
        text = "\n\nseta sv_fps \"40\"\n\n"
        assert m.parse_cfg(text) == {"sv_fps": 40}

    def test_coerces_int_types(self) -> None:
        result = m.parse_cfg('seta sv_fps "40"')
        assert isinstance(result["sv_fps"], int)


# ---------------------------------------------------------------------------
# Round-trip tests
# ---------------------------------------------------------------------------
class TestRoundTrip:
    @pytest.mark.parametrize("profile_name", list(m.PROFILES.keys()))
    def test_generate_parse_generate_is_stable(self, profile_name: str) -> None:
        profile = m.PROFILES[profile_name]
        c1 = m.generate_cfg(profile, with_header=False)
        p2 = m.parse_cfg(c1)
        c2 = m.generate_cfg(p2, with_header=False)
        assert c1 == c2, f"round-trip not stable for profile '{profile_name}'"


# ---------------------------------------------------------------------------
# Validator tests
# ---------------------------------------------------------------------------
class TestValidator:
    @pytest.mark.parametrize("profile_name", list(m.PROFILES.keys()))
    def test_built_in_profiles_validate_clean(self, profile_name: str) -> None:
        issues = m.validate(m.PROFILES[profile_name])
        assert issues == [], f"profile '{profile_name}' has issues: {issues}"

    def test_int_out_of_range(self) -> None:
        issues = m.validate({"sv_fps": 999})
        assert any("out of range" in i for i in issues)

    def test_enum_invalid_option(self) -> None:
        issues = m.validate({"vanguard_netcode_profile": "bogus"})
        assert any("not in" in i for i in issues)

    def test_unknown_cvar_flagged(self) -> None:
        issues = m.validate({"some_made_up_cvar": "value"})
        assert any("unknown cvar" in i for i in issues)

    def test_warmup_without_dowarmup_warning(self) -> None:
        issues = m.validate({"g_warmup": 60, "g_doWarmup": 0})
        assert any("g_warmup" in i and "g_doWarmup" in i for i in issues)

    def test_high_fps_without_antilag_warning(self) -> None:
        issues = m.validate({"sv_fps": 40, "g_antilag": 0})
        assert any("antilag" in i for i in issues)


# ---------------------------------------------------------------------------
# Database sanity tests
# ---------------------------------------------------------------------------
class TestDatabase:
    def test_every_cvar_has_required_fields(self) -> None:
        required = {"type", "default", "category", "description",
                    "archive", "secret"}
        for cvar, meta in m.CVARS.items():
            missing = required - set(meta.keys())
            assert not missing, f"{cvar} missing fields: {missing}"

    def test_every_cvar_has_known_category(self) -> None:
        known = {cat_id for cat_id, _ in m.CATEGORIES}
        for cvar, meta in m.CVARS.items():
            assert meta["category"] in known, \
                f"{cvar} has unknown category {meta['category']}"

    def test_every_cvar_has_known_type(self) -> None:
        valid = {"bool", "int", "string", "enum"}
        for cvar, meta in m.CVARS.items():
            assert meta["type"] in valid, \
                f"{cvar} has invalid type {meta['type']}"

    def test_enum_cvars_have_options_list(self) -> None:
        for cvar, meta in m.CVARS.items():
            if meta["type"] == "enum":
                assert isinstance(meta["range"], list), \
                    f"{cvar} is enum but range is not a list"
                assert len(meta["range"]) > 0, \
                    f"{cvar} is enum but options list is empty"

    def test_int_with_range_default_is_in_range(self) -> None:
        for cvar, meta in m.CVARS.items():
            if meta["type"] == "int" and meta["range"]:
                lo, hi = meta["range"]
                assert lo <= meta["default"] <= hi, \
                    f"{cvar} default {meta['default']} outside range [{lo}..{hi}]"

    def test_profile_keys_are_known_cvars(self) -> None:
        for profile_name, values in m.PROFILES.items():
            for cvar in values:
                assert cvar in m.CVARS, \
                    f"profile '{profile_name}' references unknown cvar '{cvar}'"
