"""Smoke tests for config-builder — package-level integration checks.

The tkinter stub installed in conftest.py makes the
``vanguard_config_builder`` package import safely on headless CI.
Per-module unit tests live in their own files; this suite holds the
integration checks that cross multiple modules.
"""
from __future__ import annotations

import pytest

import vanguard_config_builder as m


# ---------------------------------------------------------------------------
# Generator integration check (round-trip via the GUI module wrapper)
#
# Detailed unit tests for the generator live in tests/test_cfg_generator.py
# since M1 (Phase 2). This single check stays here so the smoke suite
# still exercises the wrapper -> core path end-to-end.
# ---------------------------------------------------------------------------
class TestGeneratorIntegration:
    def test_wrapper_renders_profile(self) -> None:
        text = m.generate_cfg(m.PROFILES["Cup / Tournament"], profile_name="cup")
        assert "Generated by" in text
        assert "cup" in text
        assert len(text.splitlines()) > 10


# ---------------------------------------------------------------------------
# Round-trip tests
#
# Detailed parser unit tests live in tests/test_cfg_parser.py since M2
# (Phase 2). The round-trip check stays here because it exercises
# generator + parser end-to-end through the main.py wrappers — the only
# place all three (CVARS, generator wrapper, parser wrapper) come
# together.
# ---------------------------------------------------------------------------
class TestRoundTrip:
    @pytest.mark.parametrize("profile_name", list(m.PROFILES.keys()))
    def test_generate_parse_generate_is_stable(self, profile_name: str) -> None:
        profile = m.PROFILES[profile_name]
        c1 = m.generate_cfg(profile, with_header=False)
        p2 = m.parse_cfg(c1)
        c2 = m.generate_cfg(p2, with_header=False)
        assert c1 == c2, f"round-trip not stable for profile '{profile_name}'"


# ---------------------------------------------------------------------------
# Validator integration: built-in profiles validate clean
#
# Detailed validator unit tests live in tests/test_validator.py since M3.
# This parametrized check stays here because it pins down the contract
# that all bundled profiles must validate clean against the live CVARS
# table — a guarantee that crosses module boundaries and is the natural
# home for the smoke suite.
# ---------------------------------------------------------------------------
class TestProfilesValidateClean:
    @pytest.mark.parametrize("profile_name", list(m.PROFILES.keys()))
    def test_built_in_profiles_validate_clean(self, profile_name: str) -> None:
        issues = m.validate(m.PROFILES[profile_name])
        assert issues == [], f"profile '{profile_name}' has issues: {issues}"


# ---------------------------------------------------------------------------
# Database sanity tests
# ---------------------------------------------------------------------------
class TestDatabase:
    def test_every_cvar_has_required_fields(self) -> None:
        required = {"type", "default", "category", "description",
                    "archive", "secret"}
        for cvar, meta in m.CVARS.items():
            missing = required - set(meta.keys())
            assert not missing, f"{cvar} missing fields: {missing}"

    def test_every_cvar_has_known_category(self) -> None:
        known = {cat_id for cat_id, _ in m.CATEGORIES}
        for cvar, meta in m.CVARS.items():
            assert meta["category"] in known, \
                f"{cvar} has unknown category {meta['category']}"

    def test_every_cvar_has_known_type(self) -> None:
        valid = {"bool", "int", "string", "enum"}
        for cvar, meta in m.CVARS.items():
            assert meta["type"] in valid, \
                f"{cvar} has invalid type {meta['type']}"

    def test_enum_cvars_have_options_list(self) -> None:
        for cvar, meta in m.CVARS.items():
            if meta["type"] == "enum":
                assert isinstance(meta["range"], list), \
                    f"{cvar} is enum but range is not a list"
                assert len(meta["range"]) > 0, \
                    f"{cvar} is enum but options list is empty"

    def test_int_with_range_default_is_in_range(self) -> None:
        for cvar, meta in m.CVARS.items():
            if meta["type"] == "int" and meta["range"]:
                lo, hi = meta["range"]
                assert lo <= meta["default"] <= hi, \
                    f"{cvar} default {meta['default']} outside range [{lo}..{hi}]"

    def test_profile_keys_are_known_cvars(self) -> None:
        for profile_name, values in m.PROFILES.items():
            for cvar in values:
                assert cvar in m.CVARS, \
                    f"profile '{profile_name}' references unknown cvar '{cvar}'"
