# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 wahke <info@wahke.lu> (https://wahke.lu)
# SPDX-FileCopyrightText: 2026 VanguardMod Project Contributors
"""Render a values dict into VanguardMod `server.cfg` text.

Extracted from `main.py` during Phase 2 (M1). Behavior is unchanged
from the v0.1.0 prototype; the only structural difference is that the
cvar metadata table and the tool version are now passed in as
arguments instead of being read from module globals, which makes the
function trivially unit-testable without importing the GUI module.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any


def generate_cfg(
    values: dict[str, Any],
    cvars: dict[str, dict[str, Any]],
    version: str,
    profile_name: str = "custom",
    with_header: bool = True,
) -> str:
    """Render *values* into server.cfg syntax.

    Args:
        values: Mapping of cvar name to its value.
        cvars: Cvar metadata table (the v0.1.0 ``CVARS`` dict, or the
            equivalent loaded from ``data/cvars.yaml`` in later
            milestones). Used to look up the ``archive`` flag so that
            archived cvars are emitted with ``seta`` and session-only
            cvars with ``set``. Cvars not in this table are written
            verbatim with a warning comment so that round-tripping an
            unknown-cvar config does not silently drop data.
        version: Tool version string for the metadata header.
        profile_name: Name of the active profile, written into the
            metadata header.
        with_header: Emit the metadata header block. Disable for
            deterministic round-trip tests.

    Returns:
        The full server.cfg text, terminated with a single newline.
    """
    lines: list[str] = []

    if with_header:
        lines.append("// =====================================================")
        lines.append("// VanguardMod server.cfg")
        lines.append(f"// Generated by Config Builder v{version}")
        lines.append(f"// Profile:    {profile_name}")
        lines.append(f"// Created:    {datetime.now().isoformat(timespec='seconds')}")
        lines.append("// =====================================================")
        lines.append("")

    for cvar, value in values.items():
        meta = cvars.get(cvar)
        if meta is None:
            # Unknown cvar — write it raw with a warning comment. The
            # user may have imported a cfg containing cvars we don't
            # know about yet; don't drop them silently.
            lines.append(f'// WARNING: unknown cvar "{cvar}" (preserved verbatim)')
            lines.append(f'set {cvar} "{value}"')
            continue

        prefix = "seta" if meta["archive"] else "set"
        # All values are quoted — handles spaces in strings and is harmless
        # for ints/bools.
        lines.append(f'{prefix} {cvar} "{value}"')

    lines.append("")  # trailing newline
    return "\n".join(lines)
